
name: Deploy Nginx Proxy .

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Étape 2: Configurer Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Étape 3: Se connecter à Docker Hub (ou un autre registre)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      # Étape 4: Construire l'image Docker
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: freetech4u/generic-proxy:latest

      # Étape 6: Déployer sur le serveur
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull freetech4u/generic-proxy:latest
            docker stop generic-proxy || true
            docker rm generic-proxy || true
            docker run -d -p 80:80 -p 443:443 --name generic-proxy -v /mnt/data/certs/freetech4u.fr:/etc/nginx/ssl --user root --net freetech-network freetech4u/generic-proxy:latest 
